package Restaurant;

public enum Allergeen {
    GLUTEN, EGGS, TARWE, ROGGE, GERST, HAVER, SPELT, KHORASANTARWE, SCHAALDIEREN, VIS, PINDA, SOJA, MELK, LACTOSEMELK,
    NOTEN, SELDERIJ, MOSTERD, SESAM, SULFIET, LUPINE, WEEKDIEREN;


}
